### ISSUE TITLE
Measuring impressions problem

### ISSUE THREAD

**Issue by menisck** [appfeel/analytics-google#15]
Hi!!

How can I send the impression of multiple products at once?

Every time I send analytics.trackEcommerce (options) a pageview is generated, so if I have a page in several products, I generate many pageViews as products, and this is wrong.

Thanks

**Comment by miqmago** [comment]
This is the way it tracks products if no `action` or no `category` is specified.
Normally, if you specify `action` and `category` then it should be tracked as a `HitBuilders.EventBuilder` (so it will be an event).

The problem is that `HitBuilders.HitBuilder` interface is not visible in the sdk, so when no action or no category (which are mandatory for `EventBuilder`) are specified, `ScreenViewBuilder` has to be used, which makes a pageView for each product you track.

Actually I don't see a manner to track multiple products in the same view, even in native mode. If you know how to do it, I can implement it in native interfaces and create a bridge method which you could pass an array of products and then track them at once...
